version: "3.8"

services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: "./.docker/Dockerfile"

  backend:
    build:
      context: "./backend"
      dockerfile: "./.docker/Dockerfile"
