version: "3.8"

services:
  frontend:
    build:
      target: development
    container_name: frontend_dev
    env_file: "frontend/.env"
    image: vait-melb/frontend:development
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: db_dev
    ports:
      - 5432:5432
    env_file: "db/.env"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: adminer_dev
    depends_on:
      - db
    ports:
      - 8080:8080
