service: VAIT-GOVHACK-MELBOURNE-BACKEND
frameworkVersion: '2'
configValidationMode: warn

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  memorySize: 1024
  timeout: 30
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221

custom:
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /graphql
      - http: ANY /graphql/{proxy+}
