service: VAIT-GOVHACK-MELBOURNE-BACKEND
frameworkVersion: "2"
configValidationMode: warn

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  memorySize: 1024
  timeout: 30
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  environment:
    DB_STRING: "Postgres RDS URL"
    DB_USER: ${ssm:/sls/postgres/postgres-user}
    DB_PASSWORD: ${ssm:/sls/postgres/postgres-password}

custom:
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true
  serverless-offline:
    httpPort: 5000
  serverless-offline-ssm-provider:
    file: .env

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline-ssm-provider
  - serverless-offline

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.serverelss/**"
    - "!.gitignore"
    - "!**/__pycache__/**"
    - "!.venv/**"
    - "!.requirements.zip"

functions:
  graphql:
    handler: wsgi_handler.handler
    events:
      - http:
          method: ANY
          path: /graphql
          cors: true
